FROM nginx:otel
RUN apt update && \
    apt install -y apache2-utils && \
    apt clean
COPY core/emap-portal/nginx.conf /etc/nginx/
COPY core/emap-portal/conf.d/* /etc/nginx/conf.d/
COPY core/emap-portal/www/* /usr/share/nginx/html/
RUN --mount=type=secret,id=portal-build-secrets \
    . /run/secrets/portal-build-secrets && \
    htpasswd -b -B -c /etc/nginx/conf.d/htpasswd "$PORTAL_USERNAME" "$PORTAL_PASSWORD"
